server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    location / {
        rewrite ^ /v1/index.php break;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/v1/index.php;
        fastcgi_pass php:9000;
    }
}
